resolver: lts-16.12

packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git

flags:
  xmobar:
    with_xft: true
    with_utf8: true
    with_alsa: true
    with_datezone: true
    with_threaded: true
    #all_extensions: true
  xmonad-contrib:
    use_xft: true

extra-deps: []
extra-package-dbs: []
